version: '3'
networks: # 定义网络
  dev_mrrs_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.3.0/16

services:
  # dev_mrrs_service
  dev_mrrs_service:
    # 自动重启
    restart: always
    container_name: dev_mrrs_service
    build:
      context: .
      dockerfile: ./apps/service/Dockerfile
    depends_on:
      - dev_mrrs_mysql
      - dev_mrrs_redis
    ports:
      - '8090:3001'
    networks:
      dev_mrrs_network:
        ipv4_address: 192.168.3.2

  # dev_mrrs_mysql
  dev_mrrs_mysql:
    # 自动重启
    restart: always
    container_name: dev_mrrs_mysql
    image: bitnami/mysql:latest
    # 密码认证
    environment:
      - MYSQL_ROOT_PASSWORD=Aa123456
    ports:
      - '8091:3306'
      - '8092:33060'
    volumes:
      - ./docker-volumes/mysql/data:/var/lib/mysql
      - ./docker-volumes/mysql/config:/etc/mysql/conf.d
      - ./docker-volumes/mysql/log:/var/log/mysql
      - ./docker-volumes/mysql/run:/var/run/mysqld
    networks:
      dev_mrrs_network:
        ipv4_address: 192.168.3.3

  # dev_mrrs_redis
  dev_mrrs_redis:
    # 自动重启
    restart: always
    container_name: dev_mrrs_redis
    image: bitnami/redis:latest
    # 密码认证
    environment:
      - REDIS_PASSWORD=Aa123456
    ports:
      - '6379:6379'
    volumes:
      - ./docker-volumes/redis/data:/data
      - ./docker-volumes/redis/config:/etc/redis
      - ./docker-volumes/redis/log:/var/log/redis
      - ./docker-volumes/redis/run:/var/run/redis
    networks:
      dev_mrrs_network:
        ipv4_address: 192.168.3.4

  # dev_mrrs_admin
  dev_mrrs_admin:
    # 自动重启
    restart: always
    container_name: dev_mrrs_admin
    user: root
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
    ports:
      - '8093:80'
    volumes:
      - ./docker-volumes/admin/config:/etc/nginx
      - ./docker-volumes/admin/log:/var/log/nginx
      - ./docker-volumes/admin/html:/usr/share/nginx/html
    networks:
      dev_mrrs_network:
        ipv4_address: 192.168.3.5

  # dev_mrrs_frontend_user
  dev_mrrs_frontend_user:
    # 自动重启
    restart: always
    container_name: dev_mrrs_frontend_user
    user: root
    build:
      context: .
      dockerfile: ./apps/frontend_user/Dockerfile
    ports:
      - '8094:80'
    networks:
      dev_mrrs_network:
        ipv4_address: 192.168.3.6
