/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AStyleProvider: (typeof import('ant-design-vue/es'))['StyleProvider']
    FormLayout: (typeof import('./src/components/PageLayout/FormLayout/index.vue'))['default']
    HomeContent: (typeof import('./src/components/PageLayout/HomeLayout/HomeContent.vue'))['default']
    HomeHeader: (typeof import('./src/components/PageLayout/HomeLayout/HomeHeader.vue'))['default']
    HomeLayout: (typeof import('./src/components/PageLayout/HomeLayout/index.vue'))['default']
    HomeSider: (typeof import('./src/components/PageLayout/HomeLayout/HomeSider.vue'))['default']
    LoginForm: (typeof import('./src/components/Forms/LoginForm.vue'))['default']
    RegisterForm: (typeof import('./src/components/Forms/RegisterForm.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    UpdatePasswordForm: (typeof import('./src/components/Forms/UpdatePasswordForm.vue'))['default']
    UpdateUserForm: (typeof import('./src/components/Forms/UpdateUserForm.vue'))['default']
  }
}
